// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrsgk3Xr2acVCzlEoU_0k62OIRX_bAijM',
    appId: '1:376526403547:web:16e3e03497b69eec0959fe',
    messagingSenderId: '376526403547',
    projectId: 'fluttercrud-afe54',
    authDomain: 'fluttercrud-afe54.firebaseapp.com',
    storageBucket: 'fluttercrud-afe54.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLdXTx_CMuN7LqH8hLnw0qu3SVAgHmzcE',
    appId: '1:376526403547:android:f974e92cf207fac50959fe',
    messagingSenderId: '376526403547',
    projectId: 'fluttercrud-afe54',
    storageBucket: 'fluttercrud-afe54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_QmQim66G8XsN5Lyh6EOeRNI3Jj582pE',
    appId: '1:376526403547:ios:5cc41cd3946ebf400959fe',
    messagingSenderId: '376526403547',
    projectId: 'fluttercrud-afe54',
    storageBucket: 'fluttercrud-afe54.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_QmQim66G8XsN5Lyh6EOeRNI3Jj582pE',
    appId: '1:376526403547:ios:5cc41cd3946ebf400959fe',
    messagingSenderId: '376526403547',
    projectId: 'fluttercrud-afe54',
    storageBucket: 'fluttercrud-afe54.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrudApp',
  );
}
