// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1qtZ_cTgEChdhChuf5y15pp1l7P8H0J0',
    appId: '1:442992810364:web:e030003eea6cbd92a92cf9',
    messagingSenderId: '442992810364',
    projectId: 'loginsignup-42585',
    authDomain: 'loginsignup-42585.firebaseapp.com',
    storageBucket: 'loginsignup-42585.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcNTgOEK8SwBnIyhH1Cyji7o5q_IaBacw',
    appId: '1:442992810364:android:b9d934b345160a78a92cf9',
    messagingSenderId: '442992810364',
    projectId: 'loginsignup-42585',
    storageBucket: 'loginsignup-42585.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKQiwKtFeUEqSm4zMUkOIQ_6bCo7OMgZY',
    appId: '1:442992810364:ios:11eb40ced0fa798ea92cf9',
    messagingSenderId: '442992810364',
    projectId: 'loginsignup-42585',
    storageBucket: 'loginsignup-42585.firebasestorage.app',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKQiwKtFeUEqSm4zMUkOIQ_6bCo7OMgZY',
    appId: '1:442992810364:ios:11eb40ced0fa798ea92cf9',
    messagingSenderId: '442992810364',
    projectId: 'loginsignup-42585',
    storageBucket: 'loginsignup-42585.firebasestorage.app',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1qtZ_cTgEChdhChuf5y15pp1l7P8H0J0',
    appId: '1:442992810364:web:ac2897f0524c4be0a92cf9',
    messagingSenderId: '442992810364',
    projectId: 'loginsignup-42585',
    authDomain: 'loginsignup-42585.firebaseapp.com',
    storageBucket: 'loginsignup-42585.firebasestorage.app',
  );
}
